version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brandt-webapp
    image: brandt:webapp
    ports:
      - 85:80
    extra_hosts:
      - "blog-local.com.br:172.18.0.1"
    volumes:
      - ./:/app:rw
    environment:
      - DB_HOST_CALENDARIOFTD=fasfadbaas.com.br
      - DB_USER_CALENDARIOFTD=sdfasfas
