version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brandt-webapp
    image: brandt:webapp
    ports:
      - 85:80
    extra_hosts:
      - "blog-local.com.br:172.18.0.1"
    volumes:
      - ./:/app:rw
    environment:
      - DB_HOST_CALENDARIOFTD=calendario_ftd.mysql.dbaas.com.br
      - DB_USER_CALENDARIOFTD=calendario_ftd
      - DB_PASSWORD_CALENDARIOFTD=cpcinfo
      - DB_DBNAME_CALENDARIOFTD=calendario_ftd
      - DB_PORT_CALENDARIOFTD=3306
      - CMS_ORIGIN_API=http://blog-local.com.br/portal/
